### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/Funnotate#26] opened 2023-01-21 19:02 UTC
I submitted a job and was told to be patient. I finally lost patience and sniffed around in the logs. Finally looking at docker logs for lorax I see: 
18:46:19 alignment: lorax.core.run_subprocess_with_status(PosixPath('/usr/local/var/data/L_GK8MJ0/D5F9P/alignment.stockholm'), PosixPath('/usr/local/var/data/L_GK8MJ0/D5F9P/run_log.txt'), ['time', 'nice', 'hmmalign', '--trim', '--informat', 'FASTA', '--amino', '...., PosixPath('/usr/local/var/data/L_GK8MJ0/D5F9P'), PosixPath('/usr/local/var/data/L_GK8MJ0/D5F9P/status.txt'), <function convert_stockholm_to_fasta at 0x7fa953c93820>, (PosixPath('/usr/local/var/data/L_GK8MJ0/D5F9P/alignment.faa'),)) (cd916249-fef1-4909-b2c5-fee4d4b62511)
18:46:21 Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/rq/worker.py", line 1026, in perform_job
    self.prepare_job_execution(job)
  File "/usr/local/lib/python3.8/site-packages/rq/worker.py", line 908, in prepare_job_execution
    pipeline.execute()
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 4012, in execute
    conn = self.connection_pool.get_connection('MULTI',
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 113 connecting to redis:6379. No route to host.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/rq/worker.py", line 1026, in perform_job
    self.prepare_job_execution(job)
  File "/usr/local/lib/python3.8/site-packages/rq/worker.py", line 908, in prepare_job_execution
    pipeline.execute()
  File "/usr/local/lib/python3.8/site-packages/redis/client.py", line 4012, in execute
    conn = self.connection_pool.get_connection('MULTI',
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 113 connecting to redis:6379. No route to host.
18:53:06 Cleaning registries for queue: alignment

which I will try fixing with a restart of the container. But, the user should be notified to contact someone when things are in a similarly bad way. Some proactive monitoring of the state services would probably not be amiss either, but that's a different issue.

**Comment by adf-ncgr** [comment] 2023-01-21 19:07
FWIW, restarting the containers did bring things back to proper functionality, but the need for better error handling stands.

**Comment by svengato** [comment] 2023-01-25 18:43
I had to restart the containers on the development version as well. I added some error handling and used the same sequences as you did - are they all identical? It is still asking me to be patient, but the Docker logs show no errors (yet).

**Comment by adf-ncgr** [comment] 2023-01-25 18:57
I don't recall much about the sequences I used but I don't think they caused the issue. They may have been identical or near-identical as I think they would have been representatives of the same gene from different cowpea cultivars. But I think it likely that the lorax services had just gotten into an unhealthy state at some point and I happened to be the first one to encounter it (or at least the first to complain). You might try your error handling by simply taking the lorax services down, which will likely emulate the situation I was in.

**Comment by svengato** [comment] 2023-01-25 20:10
It just posts a blank Funnotate page (the error message does not appear). But I have a couple other things to try.

**Comment by svengato** [comment] 2023-01-25 21:48
I got it to post the error message caused by taking Lorax down, and suspect that this would also handle the error you saw. Note that "Computing phylogenetic tree, please be patient" is not the same kind of error, it indicates that Lorax is not able to build the tree for the given sequences.

**Comment by svengato** [comment] 2023-01-25 21:55
> it indicates that Lorax is not able to build the tree for the given sequences.

But refuses to admit it.

**Comment by svengato** [comment] 2023-01-26 00:34
It posts different error messages depending on whether you concatenate any text (like a space) to the error. (I suspect this is an R quirk.)

Without concatenation, the message is pretty vague:

![error-without-paste](https://user-images.githubusercontent.com/8918336/214726560-4d377593-b02b-46b3-b5ed-de192d259527.png)

but with an added space (or other text) it gives a more specific hint:

![error-with-paste](https://user-images.githubusercontent.com/8918336/214726597-e9004111-c29d-48a7-a29a-71d78d876427.png)

I prefer the latter, though it is not red. (We could make it red with a style tag if desired.) We can also put a contact e-mail in the appended text.

**Comment by adf-ncgr** [comment] 2023-01-26 01:40
yes, I don't know what most of our users would do if told to check their logs. probably a suggestion to contact us combined with a specific error message is best- red or otherwise should work, but I'd suggest "Mauve! The colour of depravity in the extreme denunciation of the anilines"

**Comment by svengato** [comment] 2023-01-26 02:27
I have been waiting for an excuse to add the proustr package!

**Comment by svengato** [comment] 2023-02-03 01:59
Just a reminder after this afternoon's errors: this will require nested error detection.

**Comment by svengato** [comment] 2023-02-18 01:35
Should be fixed with commit [12e2d58](https://github.com/legumeinfo/Funnotate/commit/12e2d584dbc77584e5c577444766d01198bdbc31).

**Closed** 2023-02-23 22:06 UTC
